export const API = "https://replit.com/@AimeeCheng/pcmob6-1#main.py"
export const API_LOGIN = "/auth"
export const API_SIGNUP = "/newuser"
export const API_POSTS = "/posts"
export const API_WHOAMI = "/whoami"
export const API_CREATE = "/create"
